@baseAddress = http://localhost:5031

Post {{baseAddress}}/api/v1/files/
Accept: application/json
Content-Type: multipart/form-data; boundary=----MyBoundary

------MyBoundary
Content-Disposition: form-data; name="file"; filename="hello.txt"
Content-Type: text/plain

Hello World
------MyBoundary--

###


Delete {{baseAddress}}/api/v1/files/
Accept: application/json
Content-Type: application/json
{
  "fileName": "hello.txt"
}

###

