@baseAddress = http://localhost:5204
@exampleCategoryId = 08de0c9e-b75a-5b78-0015-5d34e4fb0000

GET {{baseAddress}}/api/categories/
Accept: application/json

###

Post {{baseAddress}}/api/categories/
Accept: application/json
Content-Type: application/json
{
    "name": "Category Deneme"
}
###

GET {{baseAddress}}/api/categories/{{exampleCategoryId}}
Accept: application/json
###
