<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Microservice_Net9_.Order.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microservice(Net9).Bus\Microservice(Net9).Bus.csproj" />
    <ProjectReference Include="..\Microservice(Net9).Order.Domain\Microservice(Net9).Order.Domain.csproj" />
  </ItemGroup>

</Project>
