<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Microservice_Net9_.Discount.Api</RootNamespace>
    <UserSecretsId>397d3e6f-8101-40b5-9d62-f9a72db11c71</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="MongoDB.EntityFrameworkCore" Version="9.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microservice(Net9).Bus\Microservice(Net9).Bus.csproj" />
    <ProjectReference Include="..\Microservice(Net9).Shared\Microservice(Net9).Shared.csproj" />
  </ItemGroup>

</Project>
